export enum ErrorTypes {
  USER_NOT_EXIST = 'USER_NOT_EXIST',
  USERNAME_EXISTS = 'USERNAME_EXISTS',
  ELSE = 'ELSE',
}

export enum AuthState {
  SIGNED_IN = 'SIGNED_IN',
  SIGNED_OUT = 'SIGNED_OUT',
  SIGNING_IN = 'SIGNING_IN',
  SIGNING_UP = 'SIGNING_UP',
  CONFIRMING_OTP = 'CONFIRMING_OTP',
  CONFIRMING_OTP_FAILED = 'CONFIRMING_OTP_FAILED',
  CONFIRMING_OTP_SUCCESS = 'CONFIRMING_OTP_SUCCESS',
  RESENDING_OTP = 'RESENDING_OTP',
  RESENDING_OTP_FAILED = 'RESENDING_OTP_FAILED',
  RESENDING_OTP_SUCCESS = 'RESENDING_OTP_SUCCESS',
  SIGNING_UP_FAILED = 'SIGNING_UP_FAILED',
  SIGNING_UP_SUCCESS = 'SIGNING_UP_SUCCESS',
  SIGNING_IN_FAILED = 'SIGNING_IN_FAILED',
  SIGNING_IN_SUCCESS = 'SIGNING_IN_SUCCESS',
  SIGNING_OUT = 'SIGNING_OUT',
  SIGNING_OUT_FAILED = 'SIGNING_OUT_FAILED',
  SIGNING_OUT_SUCCESS = 'SIGNING_OUT_SUCCESS',
}
