export enum ErrorTypes {
  USER_NOT_EXIST = 'USER_NOT_EXIST',
  USERNAME_EXISTS = 'USERNAME_EXISTS',
  ELSE = 'ELSE',
}

export enum AuthState {
  SIGNED_IN = 'SIGNED_IN',
  SIGNED_OUT = 'SIGNED_OUT',
  CONFIRMING_OTP = 'CONFIRMING_OTP',
  CONFIRMING_OTP_FAILED = 'CONFIRMING_OTP_FAILED',
  RESENDING_OTP = 'RESENDING_OTP',
  RESENDING_OTP_FAILED = 'RESENDING_OTP_FAILED',
  RESENDING_OTP_SUCCESS = 'RESENDING_OTP_SUCCESS',
  SIGNING_UP_FAILED = 'SIGNING_UP_FAILED',
  SIGNED_UP = 'SIGNING_UP',
  SIGNING_IN_FAILED = 'SIGNING_IN_FAILED',
  SIGNING_OUT_FAILED = 'SIGNING_OUT_FAILED',
}
