# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new Internal testing release to Google Play"
      lane :internal do
          previous_build_number = google_play_track_version_codes(
              package_name: "com.schmoffee",
              track: "internal",
              json_key: "app/play-store-credentials.json",
          )[0]

          current_build_number = previous_build_number + 1

          android_set_version_code(
              version_code: current_build_number
          )
          android_set_version_name(
              version_name: "0.1.#{current_build_number}"
          )

          gradle(tasks: ["clean", "bundleRelease"])

          upload_to_play_store(
              track: 'internal',
              release_status: 'draft',
              skip_upload_screenshots: true,
              skip_upload_changelogs: true,
              skip_upload_metadata: true,
              skip_upload_apk: true,
              aab: 'app/build/outputs/bundle/release/app-release.aab',
          )
      end
end

