name: Android Internal Release

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm i
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          working-directory: 'android'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
       
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: 'src'
          file: 'aws-exports.js'
          content: ${{ secrets.AWS_EXPORTS }}


      - name: Run fastlane bundle + release
        run: |
          npm run generate:build
          cd android
          bundle exec fastlane android internal --verbose
