name: Android Internal Release

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm i
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          working-directory: 'android'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
       
      - uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'aws-exports.js'
          fileDir: './src'
          encodedString: ${{ secrets.AWS_EXPORTS }}


      - name: Run fastlane bundle + release
        run: |
          cd android
          bundle exec fastlane android internal --verbose
