name: Android Internal Release

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm i
        
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          
      - run: gem install bundler
      
      - run: | 
          cd android
          bundle install --path vendor/bundle
          cd ..

      - name: Run fastlane bundle + release
        run: |
          cd android
          bundle exec fastlane android internal --verbose
