name: Android Internal Release

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm i
        
      - name: Install bundle
        run:  |
          cd android
          bundle install --path vendor/bundle
          cd ..

      - name: Run fastlane bundle + release
        run: |
          cd android
          bundle exec fastlane android internal
