name: Android Internal Release

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run npm install
        run: npm i
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          working-directory: 'android'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          
      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Run fastlane bundle + release
        run: |
          cd android
          bundle exec fastlane android internal --verbose
